from __future__ import annotations

from fastapi.testclient import TestClient

import services.sythetic_data_generation.app as app_module
from services.sythetic_data_generation.schemas import (
    ComplaintMetadata,
    SyntheticBatchOutput,
    SyntheticGenerationRequest,
    SyntheticTestCase,
)


class FakeSyntheticDataClient:
    def generate(self, request: SyntheticGenerationRequest) -> SyntheticBatchOutput:
        return SyntheticBatchOutput(
            cases=[fake_case(index) for index in range(1, request.count + 1)],
            generation_notes="Generated by test double.",
        )


def fake_case(index: int) -> SyntheticTestCase:
    complaint_document = (
        "**Channel:** Email\n"
        f"**Received:** 2026-04-2{index} 09:00 AEST\n"
        f"**Customer ID:** CUST-TEST-{index}\n"
        "**Subject:** Charged twice\n\n"
        "```\nYou charged me twice this month. Fix it and refund me.\n```"
    )
    return SyntheticTestCase(
        id=f"UNNORMALIZED-{index}",
        scenario_type="very_short_complaint",
        complaint_document=complaint_document,
        metadata=ComplaintMetadata(
            channel="Email",
            received=f"2026-04-2{index} 09:00 AEST",
            customer_id=f"CUST-TEST-{index}",
            subject="Charged twice",
        ),
        expected_category="fees_charges",
        expected_severity="medium",
        expected_routing="frontline_complaints",
        expected_sla="standard_acknowledgement",
        scenario_tags=["very_short_complaint"],
        expected_signals=["duplicate_charge", "refund_request"],
        expected_preferences=[],
        forbidden_signals=["financial_hardship", "responsible_lending", "self_harm"],
        must_detect=["duplicate_charge", "refund_request"],
        must_not_detect=["financial_hardship", "responsible_lending", "self_harm"],
    )


def install_fake_client(monkeypatch) -> None:
    monkeypatch.setattr(app_module, "client_from_env", lambda: FakeSyntheticDataClient())
    monkeypatch.setattr(app_module, "provider_from_env", lambda: "openai")
    monkeypatch.setattr(app_module, "model_from_env", lambda: "test-model")


def test_synthetic_data_generation_health_endpoint(monkeypatch) -> None:
    install_fake_client(monkeypatch)
    with TestClient(app_module.app) as client:
        response = client.get("/health")

    assert response.status_code == 200
    assert response.json()["status"] == "ok"
    assert response.json()["provider"] == "openai"


def test_generate_endpoint_returns_requested_count_and_jsonl(monkeypatch) -> None:
    install_fake_client(monkeypatch)
    request = {
        "count": 3,
        "id_prefix": "SYN-TEST",
        "scenario_focus": ["hardship", "responsible_lending"],
    }

    with TestClient(app_module.app) as client:
        response = client.post("/generate", json=request)

    assert response.status_code == 200
    body = response.json()
    assert body["requested_count"] == 3
    assert body["generated_count"] == 3
    assert len(body["cases"]) == 3
    assert len(body["jsonl"].strip().splitlines()) == 3
    assert len(body["synthetic_complaints_jsonl"].strip().splitlines()) == 3
    assert len(body["gold_labels_jsonl"].strip().splitlines()) == 3
    assert body["synthetic_generation_notes_md"].startswith("# Synthetic Data Generation Notes")
    assert body["cases"][0]["id"] == "SYN-TEST-001"
    assert body["cases"][0]["source"] == "synthetic"
    assert body["cases"][0]["expected_sla"] == "standard_acknowledgement"
    assert body["cases"][0]["expected_signals"] == ["duplicate_charge", "refund_request"]
    assert "complaint_document" in body["cases"][0]
    assert "**Channel:**" in body["cases"][0]["complaint_document"]
    gold_label = body["gold_labels_jsonl"].strip().splitlines()[0]
    assert '"expected_signals":["duplicate_charge","refund_request"]' in gold_label
    assert '"forbidden_signals":["financial_hardship","responsible_lending","self_harm"]' in gold_label
