"""create triage service tables

Revision ID: bf6859228770
Revises: 
Create Date: 2026-06-13 10:26:21.767719
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'bf6859228770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('complaint_document', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.Text(), nullable=True),
    sa.Column('input_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acknowledgement_draft', sa.Text(), nullable=False),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id'),
    schema='triage_service'
    )
    op.create_index('idx_triage_runs_complaint_id', 'triage_runs', ['complaint_id'], unique=False, schema='triage_service')
    op.create_index('idx_triage_runs_created_at', 'triage_runs', ['created_at'], unique=False, schema='triage_service')
    op.create_index('idx_triage_runs_version_created', 'triage_runs', ['version', 'created_at'], unique=False, schema='triage_service')
    op.create_table('triage_reviews',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('final_category', sa.Text(), nullable=True),
    sa.Column('final_severity', sa.Text(), nullable=True),
    sa.Column('final_routing', sa.Text(), nullable=True),
    sa.Column('edited_acknowledgement', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('review_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('accepted', 'edited', 'rejected')", name='ck_triage_reviews_status'),
    sa.ForeignKeyConstraint(['run_id'], ['triage_service.triage_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id'),
    schema='triage_service'
    )
    op.create_index('idx_triage_reviews_status_updated', 'triage_reviews', ['status', 'updated_at'], unique=False, schema='triage_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_triage_reviews_status_updated', table_name='triage_reviews', schema='triage_service')
    op.drop_table('triage_reviews', schema='triage_service')
    op.drop_index('idx_triage_runs_version_created', table_name='triage_runs', schema='triage_service')
    op.drop_index('idx_triage_runs_created_at', table_name='triage_runs', schema='triage_service')
    op.drop_index('idx_triage_runs_complaint_id', table_name='triage_runs', schema='triage_service')
    op.drop_table('triage_runs', schema='triage_service')
    # ### end Alembic commands ###
