"""Typer CLI for ConvFinQA chat."""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional
from uuid import uuid4

import requests
import typer
from dotenv import load_dotenv
from rich import box
from rich import print as rich_print
from rich.console import Console
from rich.table import Table

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")
load_dotenv(ROOT / "services/chatbot/.env", override=False)

SESSION_MAP_PATH = Path(__file__).resolve().parent / ".chat_sessions.json"
console = Console()

app = typer.Typer(
    name="main",
    help="CLI for the ConvFinQA chatbot service",
    add_completion=True,
    no_args_is_help=True,
)


def chatbot_base_url() -> str:
    return (os.getenv("CHATBOT_API_URL") or "http://localhost:8080").rstrip("/")


def chatbot_api_key() -> str | None:
    return os.getenv("CHATBOT_API_KEY") or os.getenv("RERANKER_API_KEY")


def chat_headers() -> dict[str, str]:
    headers = {"Content-Type": "application/json"}
    api_key = chatbot_api_key()
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    return headers


def autogenerated_label() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"cli-{timestamp}-{uuid4().hex[:8]}"


def load_session_map() -> dict[str, str]:
    if not SESSION_MAP_PATH.exists():
        return {}
    try:
        payload = json.loads(SESSION_MAP_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(payload, dict):
        return {}
    return {
        str(label): str(conversation_id)
        for label, conversation_id in payload.items()
        if isinstance(label, str) and isinstance(conversation_id, str)
    }


def save_session_map(session_map: dict[str, str]) -> None:
    SESSION_MAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    SESSION_MAP_PATH.write_text(
        json.dumps(session_map, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def parse_markdown_table(markdown: str) -> tuple[list[str], list[list[str]]] | None:
    lines = [line.strip() for line in markdown.splitlines() if line.strip()]
    table_lines = [
        line for line in lines if line.startswith("|") and line.endswith("|")
    ]
    if len(table_lines) < 2:
        return None

    rows = [
        [cell.strip() for cell in line.strip("|").split("|")] for line in table_lines
    ]
    separator = rows[1]
    if not all(set(cell.replace(":", "").strip()) <= {"-"} for cell in separator):
        return None

    return rows[0], rows[2:]


def is_number(value: str) -> bool:
    normalized = value.replace(",", "").replace("%", "").strip()
    if not normalized:
        return False
    try:
        float(normalized)
    except ValueError:
        return False
    return True


def print_reference_block(text: str) -> None:
    parsed_table = parse_markdown_table(text)
    if parsed_table is None:
        rich_print(text)
        return

    headers, rows = parsed_table
    table = Table(box=box.SIMPLE_HEAVY, show_lines=False, pad_edge=False)
    for column_index, header in enumerate(headers):
        values = [row[column_index] for row in rows if column_index < len(row)]
        justify = (
            "right" if values and all(is_number(value) for value in values) else "left"
        )
        table.add_column(header, justify=justify, no_wrap=True)
    for row in rows:
        table.add_row(*row)
    console.print(table)


def print_context_references(
    context: list[dict[str, Any]],
    limit: int,
) -> None:
    if not context:
        return
    seen: set[tuple[str, str]] = set()
    visible_context: list[dict[str, Any]] = []
    for item in context:
        content = str(item.get("content") or "").strip()
        table_markdown = str(item.get("table_markdown") or "").strip()
        dedupe_key = (content, table_markdown)
        if dedupe_key in seen:
            continue
        seen.add(dedupe_key)
        visible_context.append(item)
        if len(visible_context) >= max(limit, 0):
            break
    if not visible_context:
        return
    rich_print(
        f"[bold]references[/bold] [dim](top {len(visible_context)} unique of {len(context)})[/dim]"
    )
    for index, item in enumerate(visible_context, start=1):
        doc_id = item.get("doc_id") or "unknown-doc"
        source_type = item.get("source_type") or "unknown-source"
        content = str(item.get("content") or "").strip()
        table_markdown = str(item.get("table_markdown") or "").strip()
        rich_print(f"\n[dim][{index}] {doc_id} ({source_type})[/dim]")
        if content:
            print_reference_block(content)
        if table_markdown and table_markdown != content:
            print_reference_block(table_markdown)


@app.command()
def chat(
    label: Optional[str] = typer.Argument(  # noqa: UP007,UP045
        None,
        help="Optional conversation label. Reusing a label resumes the saved conversation.",
    ),
    user_name: str = typer.Option(
        "cli-user",
        "--user",
        help="User name sent to the chatbot service",
    ),
    show_context: bool = typer.Option(
        False,
        "--show-context",
        help="Print returned context references after each answer",
    ),
    references: int = typer.Option(
        2,
        "--references",
        min=0,
        help="Number of top returned context references to print with --show-context",
    ),
) -> None:
    """Open an interactive chat session backed by the `/chat` service."""
    label_was_supplied = bool((label or "").strip())
    conversation_label = (label or "").strip() or autogenerated_label()
    session_map = load_session_map()
    conversation_id = (
        session_map.get(conversation_label) if label_was_supplied else None
    )
    rich_print(
        f"[dim]chatbot[/dim] {chatbot_base_url()}/chat [dim]label={conversation_label}[/dim]"
    )
    if conversation_id:
        rich_print(
            f"[dim]resuming conversation_id={conversation_id} from {SESSION_MAP_PATH.name}[/dim]"
        )
    rich_print("[dim]type `exit` or `quit` to stop[/dim]")

    while True:
        try:
            message = input(">>> ")
        except EOFError:
            rich_print()
            break

        if message.strip().lower() in {"exit", "quit"}:
            break
        if not message.strip():
            continue

        payload: dict[str, Any] = {
            "user_name": user_name,
            "message": message,
            "title": conversation_label if conversation_id is None else None,
            "metadata": {
                "label": conversation_label,
                "source": "cli",
            },
        }
        if conversation_id is not None:
            payload["conversation_id"] = conversation_id

        try:
            response = requests.post(
                f"{chatbot_base_url()}/chat",
                headers=chat_headers(),
                json=payload,
                timeout=300,
            )
            response.raise_for_status()
        except requests.HTTPError as exc:
            detail = exc.response.text if exc.response is not None else str(exc)
            rich_print(f"[red][bold]error:[/bold] HTTP failure[/red] {detail}")
            continue
        except requests.RequestException as exc:
            rich_print(f"[red][bold]error:[/bold] request failed[/red] {exc}")
            continue

        body = response.json()
        conversation_id = body.get("conversation_id") or conversation_id
        if label_was_supplied and conversation_id:
            session_map[conversation_label] = conversation_id
            save_session_map(session_map)
        output = body.get("output") or {}
        answer = output.get("answer") or ""
        confidence = output.get("confidence_score")
        context = output.get("context") or []

        confidence_suffix = (
            f" [dim](confidence={float(confidence):.2f})[/dim]"
            if confidence is not None
            else ""
        )
        rich_print(f"[blue][bold]assistant:[/bold] {answer}[/blue]{confidence_suffix}")
        if show_context:
            print_context_references(context, references)


if __name__ == "__main__":
    app()
